# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alphonsus
email: m.alfonz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full-stack web developer by day, indie game developer by night.
baseurl: "" # the subpath of your site, e.g. /blog
url: "alphonsus.github.io" # the base hostname & protocol for your site
twitter_username: alphnsus
github_username:  alfonzm

# Build settings
markdown: kramdown
highlight: rouge

# Outputting
permalink: /:title/